[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
options = "FAVENgBXzD9K9qYHKRF5RFRJeT4Qa2EV4EoTycki5gGT"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/faven-dev.json"

[scripts]
test = "cargo test"

[hooks]

[path]
options = "~/.config/solana/FAVENgBXzD9K9qYHKRF5RFRJeT4Qa2EV4EoTycki5gGT-program.json"
